# frozen_string_literal: true
source "https://rubygems.org"

# gem "rails"
gem 'capybara'
gem 'cucumber'
gem 'minitest'
gem 'omniauth-twitter'
gem 'rake'
gem 'rspec'
gem 'simplecov'
gem 'sinatra'
gem 'sqlite3'
gem 'thin'
gem 'twitter'
gem 'uk_postcode'
