Feature: Location System

  Scenario: Not logged in on menu page
    Given I am on the menu page
    Then I should see "Sign in with Twitter"
    Then I should see the image "/images/logo/logo_full_2.svg"
    Then I should see the image "/images/logo/logo_text_white.svg"
    Then I should see "MENU DEALS ORDER" within "#desktop_menu"
    When I follow "MENU" within "#desktop_menu"
    Then I should be on the menu page
    Then I should see "Our Menu"
    Then I should see "Sheffield" within ".nav-pills"
    Then I should see "London" within ".nav-pills"
    Then I should see the image "/images/pizza/london/texas_bbq.png"
    Then I should see the image "/images/pizza/pepperoni.png"
    Then I should see the image "/images/pizza/sheffield/mighty_meaty.png"
    Then I should see the image "/images/pizza/new_yorker.png"
    Then I should see the image "/images/pizza/ham_pineapple.png"
    Then I should see "Sign in to Add to Basket"
    Then I should see "Ham & Pineapple"
    Then I should see "Regular base with ham and pineapple toppings"
    Then I should not see "Small £8.99"
    Then I should see the image "/images/logo/logo_text.svg"
    Then I should see "About Us Contact Us Accessibility" within ".footer_nav"
    Then I should not see "Control Panel" within ".footer_nav"
    Then I should see "Group 31, Team Software Project, 2017" within "footer"

  Scenario: Normal User logged in on menu page
    Given I am on the menu page
    Then I should see "Sign in with Twitter"
    And I want to sign in as user
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, ZerJun Eng"
    Then I should see the image "/images/logo/logo_full_2.svg"
    Then I should see the image "/images/logo/logo_text_white.svg"
    Then I should see "MENU DEALS ORDER" within "#desktop_menu"
    When I follow "MENU" within "#desktop_menu"
    Then I should be on the menu page
    Then I should see "Our Menu"
    Then I should see "Sheffield" within ".nav-pills"
    Then I should not see "London" within ".nav-pills"
    Then I should not see the image "/images/pizza/london/texas_bbq.png"
    Then I should see the image "/images/pizza/pepperoni.png"
    Then I should see the image "/images/pizza/sheffield/mighty_meaty.png"
    Then I should see the image "/images/pizza/new_yorker.png"
    Then I should see the image "/images/pizza/ham_pineapple.png"
    Then I should see "Ham & Pineapple"
    Then I should see "Regular base with ham and pineapple toppings"
    Then I should see "Small £8.99"
    Then I should see the image "/images/logo/logo_text.svg"
    Then I should see "About Us Contact Us Accessibility" within ".footer_nav"
    Then I should not see "Control Panel" within ".footer_nav"
    Then I should see "Group 31, Team Software Project, 2017" within "footer"

  Scenario: Too far user logged in on menu page
    Given I am on the menu page
    Then I should see "Sign in with Twitter"
    And I want to sign in as away user
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Andreak"
    Then I should see the image "/images/logo/logo_full_2.svg"
    Then I should see the image "/images/logo/logo_text_white.svg"
    Then I should see "MENU DEALS ORDER" within "#desktop_menu"
    When I follow "MENU" within "#desktop_menu"
    Then I should be on the menu page
    Then I should see "Our Menu"
    Then I should see "We're sorry. Unfortunately, we do not operate in Manchester, England at the moment." within "#warning"
    Then I should see "Sheffield" within ".nav-pills"
    Then I should see "London" within ".nav-pills"
    Then I should see the image "/images/pizza/london/texas_bbq.png"
    Then I should see the image "/images/pizza/pepperoni.png"
    Then I should see the image "/images/pizza/sheffield/mighty_meaty.png"
    Then I should see the image "/images/pizza/new_yorker.png"
    Then I should see "New Yorker"
    Then I should see "Pepperoni, ham, bacon, mushrooms"
    Then I should see "Small £8.99"
    Then I should see the image "/images/pizza/ham_pineapple.png"
    Then I should see the image "/images/logo/logo_text.svg"
    Then I should see "About Us Contact Us Accessibility" within ".footer_nav"
    Then I should not see "Control Panel" within ".footer_nav"
    Then I should see "Group 31, Team Software Project, 2017" within "footer"

  Scenario: London user logged in on menu page
    Given I am on the menu page
    Then I should see "Sign in with Twitter"
    And I want to sign in as London user
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Pizza31 LON"
    Then I should see the image "/images/logo/logo_full_2.svg"
    Then I should see the image "/images/logo/logo_text_white.svg"
    Then I should see "MENU DEALS ORDER" within "#desktop_menu"
    When I follow "MENU" within "#desktop_menu"
    Then I should be on the menu page
    Then I should see "Our Menu"
    Then I should not see "Sheffield" within ".nav-pills"
    Then I should see "London" within ".nav-pills"
    Then I should see the image "/images/pizza/london/texas_bbq.png"
    Then I should see "Texas BBQ"
    Then I should see "BBQ sauce topped with smoky bacon, succulent roast chicken, red onions, green and red peppers"
    Then I should see "Medium £14.99"
    Then I should see the image "/images/pizza/pepperoni.png"
    Then I should not see the image "/images/pizza/sheffield/mighty_meaty.png"
    Then I should see the image "/images/pizza/new_yorker.png"
    Then I should see the image "/images/pizza/ham_pineapple.png"
    Then I should see the image "/images/logo/logo_text.svg"
    Then I should see "About Us Contact Us Accessibility" within ".footer_nav"
    Then I should not see "Control Panel" within ".footer_nav"
    Then I should see "Group 31, Team Software Project, 2017" within "footer"

  Scenario: Sheffield user logged in on menu page
    Given I am on the menu page
    Then I should see "Sign in with Twitter"
    And I want to sign in as admin
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Pizza31"
    Then I should see the image "/images/logo/logo_full_2.svg"
    Then I should see the image "/images/logo/logo_text_white.svg"
    Then I should see "MENU DEALS ORDER" within "#desktop_menu"
    When I follow "MENU" within "#desktop_menu"
    Then I should be on the menu page
    Then I should see "Our Menu"
    Then I should see "Sheffield" within ".nav-pills"
    Then I should not see "London" within ".nav-pills"
    Then I should not see the image "/images/pizza/london/texas_bbq.png"
    Then I should see the image "/images/pizza/pepperoni.png"
    Then I should see the image "/images/pizza/sheffield/mighty_meaty.png"
    Then I should see "Mighty Meaty"
    Then I should see "Tomato sauce, pepperoni, ham, ground beef, sausage, red onions, mushrooms and mozzarella cheese"
    Then I should see "Medium £14.99"
    Then I should see the image "/images/pizza/new_yorker.png"
    Then I should see the image "/images/pizza/ham_pineapple.png"
    Then I should see the image "/images/logo/logo_text.svg"
    Then I should see "About Us Contact Us Accessibility" within ".footer_nav"
    Then I should see "Control Panel" within ".footer_nav"
    Then I should see "Group 31, Team Software Project, 2017" within "footer"
