Feature: Control Panel for Menu. Accessibile only for admin

Scenario: Logged in as admin on control panel/menu, adding three pizzas
    Given I am on the homepage
    And I want to sign in as admin
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Pizza31"
    Then I should see "Control Panel" within ".footer_nav"
    When I go to the control panel page
    When I follow "Menu" within ".navbar-collapse"
    Then I should be on the menu control panel page
    Then I should see "Location Category Name Description Allergen Information Image"
    Then I should see "Both Regular Pepperoni Regular base with pepperoni topping Gluten, milk"
    Then I should see "London Special Texas BBQ"
    Then I should see "Sheffield Special Mighty Meaty"
    Then I should see "Add Pizza"
    Then I should see "Edit Pizza"
    Then I should see "Delete Pizza"
    Then I should see "Category Pricing"
    When I choose "London" within ".add_pizza"
    When I choose "Special" within ".add_pizza"
    When I fill in "name" with "Test Pizza" within ".add_pizza"
    When I fill in "description" with "Test Pizza Description" within ".add_pizza"
    When I fill in "allergen_info" with "No allergen" within ".add_pizza"
    When I attach the file "../pizza31/public/images/pizza/pepperoni.png" to "image_path" within ".add_pizza"
    When I press "add-pizza" within ".add_pizza"
    Then I should see "New pizza has been added into the database"
    Then I should see "London Special Test Pizza Test Pizza Description No allergen"
    Then I should see the image "../images/pizza/pepperoni.png"
    When I choose "Sheffield" within ".add_pizza"
    When I choose "Regular" within ".add_pizza"
    When I fill in "name" with "Test Pizza2" within ".add_pizza"
    When I fill in "description" with "Test Pizza2 Description" within ".add_pizza"
    When I fill in "allergen_info" with "Test Allergen" within ".add_pizza"
    When I attach the file "../pizza31/public/images/pizza/london/texas_bbq.png" to "image_path" within ".add_pizza"
    When I press "add-pizza" within ".add_pizza"
    Then I should see "New pizza has been added into the database"
    Then I should see "Sheffield Regular Test Pizza2 Test Pizza2 Description Test Allergen"
    Then I should see the image "../images/pizza/london/texas_bbq.png"
    When I choose "Both" within ".add_pizza"
    When I choose "Regular" within ".add_pizza"
    When I fill in "name" with "Test Pizza3" within ".add_pizza"
    When I fill in "description" with "Test Pizza3 Description" within ".add_pizza"
    When I fill in "allergen_info" with "Test Allergen3" within ".add_pizza"
    When I attach the file "../pizza31/public/images/pizza/hawaiian.png" to "image_path" within ".add_pizza"
    When I press "add-pizza" within ".add_pizza"
    Then I should see "New pizza has been added into the database"
    Then I should see "Both Regular Test Pizza3 Test Pizza3 Description Test Allergen3"
    Then I should see the image "../images/pizza/hawaiian.png"

Scenario: Logged in as admin on control panel/menu, adding a duplicate pizza
    Given I am on the homepage
    And I want to sign in as admin
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Pizza31"
    Then I should see "Control Panel" within ".footer_nav"
    When I go to the control panel page
    When I follow "Menu" within ".navbar-collapse"
    Then I should be on the menu control panel page
    Then I should see "Location Category Name Description Allergen Information Image"
    Then I should see "Both Regular Pepperoni Regular base with pepperoni topping Gluten, milk"
    Then I should see "London Special Test Pizza Test Pizza Description No allergen"
    Then I should see "Sheffield Regular Test Pizza2 Test Pizza2 Description Test Allergen"
    Then I should see "Add Pizza"
    Then I should see "Edit Pizza"
    Then I should see "Delete Pizza"
    Then I should see "Category Pricing"
    When I choose "London" within ".add_pizza"
    When I choose "Special" within ".add_pizza"
    When I fill in "name" with "Test Pizza" within ".add_pizza"
    When I fill in "description" with "Test Pizza Description" within ".add_pizza"
    When I fill in "allergen_info" with "No allergen" within ".add_pizza"
    When I attach the file "../pizza31/public/images/pizza/pepperoni.png" to "image_path" within ".add_pizza"
    When I press "add-pizza" within ".add_pizza"
    Then I should see "The pizza already exists in the database"
    Then I should see "London Special Test Pizza Test Pizza Description No allergen"
    Then I should see the image "../images/pizza/pepperoni.png"

  Scenario: Logged in as admin on control panel/menu, editing pizza information
    Given I am on the homepage
    And I want to sign in as admin
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Pizza31"
    Then I should see "Control Panel" within ".footer_nav"
    When I go to the control panel page
    When I follow "Menu" within ".navbar-collapse"
    Then I should be on the menu control panel page
    Then I should see "Location Category Name Description Allergen Information Image"
    Then I should see "Both Regular Pepperoni Regular base with pepperoni topping Gluten, milk"
    Then I should see "London Special Test Pizza Test Pizza Description No allergen"
    Then I should see "Sheffield Regular Test Pizza2 Test Pizza2 Description Test Allergen"
    Then I should see "Add Pizza"
    Then I should see "Edit Pizza"
    Then I should see "Delete Pizza"
    Then I should see "Category Pricing"
    When I select "Test Pizza2" from "pizza_id" within ".edit_pizza"
    When I press "get-edit-info" within ".edit_pizza"
    When I choose "Both" within ".edit_pizza"
    When I choose "Regular" within ".edit_pizza"
    When I fill in "name" with "Test Pizza 2" within ".edit_pizza"
    When I fill in "description" with "Test Pizza 2 Description" within ".edit_pizza"
    When I attach the file "../pizza31/public/images/pizza/sheffield/mighty_meaty.png" to "image_path" within ".edit_pizza"
    When I press "edit-pizza" within ".edit_pizza"
    Then I should see "The changes have been saved"
    Then I should see "Both Regular Test Pizza 2 Test Pizza 2 Description Test Allergen"
    Then I should see the image "../images/pizza/sheffield/mighty_meaty.png"
    Then I should not see "Test Pizza2"
    Then I should not see "Test Pizza2 Description"
    Then I should not see "Sheffield Regular Test Pizza2 Test Pizza2 Description Test Allergen"
    When I select "Test Pizza" from "pizza_id" within ".edit_pizza"
    When I press "get-edit-info" within ".edit_pizza"
    When I choose "Sheffield" within ".edit_pizza"
    When I choose "Special" within ".edit_pizza"
    When I fill in "description" with "Test Pizza Description Edited" within ".edit_pizza"
    When I press "edit-pizza" within ".edit_pizza"
    Then I should see "The changes have been saved"
    When I select "Test Pizza" from "pizza_id" within ".edit_pizza"
    When I press "get-edit-info" within ".edit_pizza"
    When I choose "London" within ".edit_pizza"
    When I press "edit-pizza" within ".edit_pizza"
    Then I should see "The changes have been saved"
    When I select "Test Pizza" from "pizza_id" within ".edit_pizza"
    When I press "get-edit-info" within ".edit_pizza"
    When I choose "Sheffield" within ".edit_pizza"
    When I press "edit-pizza" within ".edit_pizza"
    Then I should see "The changes have been saved"
    Then I should see "Sheffield Special Test Pizza Test Pizza Description Edited No allergen"
    Then I should not see "London Special Test Pizza Test Pizza Description No allergen"

  Scenario: Logged in as admin on control panel/menu, editing duplicate pizza information
    Given I am on the homepage
    And I want to sign in as admin
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Pizza31"
    Then I should see "Control Panel" within ".footer_nav"
    When I go to the control panel page
    When I follow "Menu" within ".navbar-collapse"
    Then I should be on the menu control panel page
    Then I should see "Location Category Name Description Allergen Information Image"
    Then I should see "Both Regular Pepperoni Regular base with pepperoni topping Gluten, milk"
    Then I should see "Sheffield Special Test Pizza Test Pizza Description Edited No allergen"
    Then I should see "Both Regular Test Pizza 2 Test Pizza 2 Description Test Allergen"
    Then I should see "Add Pizza"
    Then I should see "Edit Pizza"
    Then I should see "Delete Pizza"
    Then I should see "Category Pricing"
    When I select "Test Pizza 2" from "pizza_id" within ".edit_pizza"
    When I press "get-edit-info" within ".edit_pizza"
    When I fill in "name" with "Test Pizza" within ".edit_pizza"
    When I press "edit-pizza" within ".edit_pizza"
    Then I should see "The same pizza name already exists"
    Then I should not see "Both Regular Test Pizza Test Pizza 2 Description Test Allergen"
    Then I should see "Both Regular Test Pizza 2 Test Pizza 2 Description Test Allergen"

  Scenario: Logged in as admin on control panel/menu, delete multiple pizzas
    Given I am on the homepage
    And I want to sign in as admin
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Pizza31"
    Then I should see "Control Panel" within ".footer_nav"
    When I go to the control panel page
    When I follow "Menu" within ".navbar-collapse"
    Then I should be on the menu control panel page
    Then I should see "Location Category Name Description Allergen Information Image"
    Then I should see "Both Regular Pepperoni Regular base with pepperoni topping Gluten, milk"
    Then I should see "Sheffield Special Test Pizza Test Pizza Description Edited No allergen"
    Then I should see "Both Regular Test Pizza 2 Test Pizza 2 Description Test Allergen"
    Then I should see "Add Pizza"
    Then I should see "Edit Pizza"
    Then I should see "Delete Pizza"
    Then I should see "Category Pricing"
    Then I should see "Warning: You will have to add the pizza again after deletion"
    When I select "Test Pizza" from "pizza_id[]" within ".delete_pizza"
    When I select "Test Pizza 2" from "pizza_id[]" within ".delete_pizza"
    When I select "Test Pizza3" from "pizza_id[]" within ".delete_pizza"
    When I check "Confirm for deletion"
    When I press "delete-pizza" within ".delete_pizza"
    Then I should see "The selected pizza has been deleted"
    Then I should not see "Sheffield Special Test Pizza Test Pizza Description No allergen"
    Then I should not see "Both Regular Test Pizza 2 Test Pizza 2 Description Test Allergen"

  Scenario: Logged in as admin on control panel/menu, edit category pricing(regular)
    Given I am on the homepage
    And I want to sign in as admin
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Pizza31"
    Then I should see "Control Panel" within ".footer_nav"
    When I go to the control panel page
    When I follow "Menu" within ".navbar-collapse"
    Then I should be on the menu control panel page
    Then I should see "Location Category Name Description Allergen Information Image"
    Then I should see "Add Pizza"
    Then I should see "Edit Pizza"
    Then I should see "Delete Pizza"
    Then I should see "Category Pricing"
    When I select "Regular" from "category_id" within ".edit_pricing"
    When I press "get-pricing" within ".edit_pricing"
    Then the "small_price" field within ".edit_pricing" should contain "8.99"
    When I fill in "small_price" with "9.99" within ".edit_pricing"
    When I press "edit-pricing" within ".edit_pricing"
    Then I should see "The prices have been saved"
    When I select "Regular" from "category_id" within ".edit_pricing"
    When I press "get-pricing" within ".edit_pricing"
    Then the "small_price" field within ".edit_pricing" should not contain "8.99"
    Then the "small_price" field within ".edit_pricing" should contain "9.99"
    When I fill in "small_price" with "8.99" within ".edit_pricing"
    When I press "edit-pricing" within ".edit_pricing"
    Then I should see "The prices have been saved"

  Scenario: Logged in as admin on control panel/menu, edit category pricing(special)
    Given I am on the homepage
    And I want to sign in as admin
    When I follow "Sign in with Twitter" within "#desktop_header"
    Then I should see "Hello, Pizza31"
    Then I should see "Control Panel" within ".footer_nav"
    When I go to the control panel page
    When I follow "Menu" within ".navbar-collapse"
    Then I should be on the menu control panel page
    Then I should see "Location Category Name Description Allergen Information Image"
    Then I should see "Add Pizza"
    Then I should see "Edit Pizza"
    Then I should see "Delete Pizza"
    Then I should see "Category Pricing"
    When I select "Special" from "category_id" within ".edit_pricing"
    When I press "get-pricing" within ".edit_pricing"
    Then the "small_price" field within ".edit_pricing" should contain "10.99"
    When I fill in "small_price" with "11.99" within ".edit_pricing"
    When I press "edit-pricing" within ".edit_pricing"
    Then I should see "The prices have been saved"
    When I select "Special" from "category_id" within ".edit_pricing"
    When I press "get-pricing" within ".edit_pricing"
    Then the "small_price" field within ".edit_pricing" should not contain "10.99"
    Then the "small_price" field within ".edit_pricing" should contain "11.99"
    When I fill in "small_price" with "10.99" within ".edit_pricing"
    When I press "edit-pricing" within ".edit_pricing"
    Then I should see "The prices have been saved"
